# Generated by Django 3.0.7 on 2020-07-05 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employees', to='CBV_app.Company'),
        ),
    ]
